-- Interview Details Table
CREATE TABLE INTERVIEW_DETAILS 
(
    INTERVIEW_ID NUMBER DEFAULT INTERVIEW_DETAILS_SEQ.NEXTVAL,
    INTERVIEW_DATE DATE,
    INTERVIEWER_NAME VARCHAR2(100),

    CONSTRAINT INTERVIEW_DETAILS_PK PRIMARY KEY(INTERVIEW_ID)
);

-- Application Status Table
CREATE TABLE APPLICATION_STATUS 
(
    STATUS_ID NUMBER DEFAULT APPLICATION_STATUS_SEQ.NEXTVAL,
    STATUS_NAME VARCHAR2(50),
    STATUS_LAST_UPDATE DATE,
    STATUS_ISFINAL CHAR(1),

    CONSTRAINT APPLICATION_STATUS_PK PRIMARY KEY(STATUS_ID)
);

-- Applications Table
CREATE TABLE APPLICATIONS 
(
    APPLICATION_ID NUMBER DEFAULT APPLICATIONS_SEQ.NEXTVAL,
    JOB_ID NUMBER,
    JOB_SEEKER_ID NUMBER,
    INTERVIEW_ID NUMBER,
    DATE_APPLIED DATE DEFAULT SYSDATE,
    STATUS_ID NUMBER,

    CONSTRAINT APPLICATIONS_PK PRIMARY KEY(APPLICATION_ID),
    CONSTRAINT APPLICATIONS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT APPLICATIONS_SEEKERS_FK FOREIGN KEY (JOB_SEEKER_ID) REFERENCES JOB_SEEKERS(JOB_SEEKER_ID) ON DELETE CASCADE,
    CONSTRAINT APPLICATIONS_IVDETAILS_FK FOREIGN KEY (INTERVIEW_ID) REFERENCES INTERVIEW_DETAILS(INTERVIEW_ID) ON DELETE CASCADE,
    CONSTRAINT APPLICATIONS_APPSTATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES APPLICATION_STATUS(STATUS_ID) ON DELETE CASCADE
);

-- Feedbacks Table
CREATE TABLE FEEDBACKS 
(
    FEEDBACK_ID NUMBER DEFAULT FEEDBACKS_SEQ.NEXTVAL,
    APPLICATION_ID NUMBER,
    MESSAGE CLOB,
    DATE_SENT DATE DEFAULT SYSDATE,

    CONSTRAINT FEEDBACKS_PK PRIMARY KEY(FEEDBACK_ID),
    CONSTRAINT FEEDBACKS_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID) ON DELETE CASCADE
);

-- Application Feedback Junction Table
CREATE TABLE APP_FEEDBACK 
(
    APPLICATION_ID NUMBER,
    FEEDBACK_ID NUMBER,

    CONSTRAINT APP_FEEDBACK_PK PRIMARY KEY (APPLICATION_ID, FEEDBACK_ID),
    CONSTRAINT APP_FEEDBACK_APPLICATIONS_FK FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID),
    CONSTRAINT APP_FEEDBACK_FEEDBACKS_FK FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACKS(FEEDBACK_ID)
);

