-- Company Profile Table
CREATE TABLE COMPANY_PROFILE 
(
    COMPANY_ID NUMBER DEFAULT COMPANY_PROFILE_SEQ.NEXTVAL,
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    COMPANY_ADDRESS VARCHAR2(200),
    COMPANY_SPECIALTY VARCHAR2(100),
    COMPANY_REQUIREMENTS VARCHAR2(500),
    COMPANY_BASE_SALARY NUMBER,
    COMPANY_PHONE_NUMBER VARCHAR2(20),
    COMPANY_SIZE NUMBER,

    CONSTRAINT COMPANY_PROFILE_PK PRIMARY KEY (COMPANY_ID)
);

-- Company Branches Table
CREATE TABLE COMPANY_BRANCHES 
(
    BRANCHES_ID NUMBER DEFAULT COMPANY_BRANCHES_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    BRANCH_ADDRESS VARCHAR2(200),
    BRANCH_SPECIALTY VARCHAR2(100),
    BRANCH_PHONE_NUMBER VARCHAR2(20),
    BRANCH_SIZE NUMBER,

    CONSTRAINT COMPANY_BRANCHES_PK PRIMARY KEY (BRANCHES_ID),
    CONSTRAINT BRANCHES_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE
);

-- Company Department Table
CREATE TABLE COMPANY_DEPARTMENT
(
    DEPARTMENT_ID NUMBER DEFAULT COMPANY_DEPARTMENT_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    DEPARTMENT_SPECIALTY VARCHAR2(100),
    DEPARTMENT_SIZE NUMBER,
    DEPARTMENT_PHONE_NUMBER VARCHAR2(20),
    DEPARTMENT_NAME VARCHAR2(100),

    CONSTRAINT COMPANY_DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT DEPARTMENT_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE
);

-- Company Socials Table
CREATE TABLE COMPANY_SOCIALS 
(
    SOCIAL_PLATFORM_ID NUMBER DEFAULT COMPANY_SOCIALS_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    COMPANY_WEBSITE VARCHAR2(200),
    COMPANY_APP VARCHAR2(100),
    COMPANY_SOCIAL_APPS VARCHAR2(200),

    CONSTRAINT COMPANY_SOCIALS_PK PRIMARY KEY(SOCIAL_PLATFORM_ID),
    CONSTRAINT SOCIALS_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE
);

-- Jobs Offered on Socials Table
CREATE TABLE JOBS_OFFERED_ON_SOCIALS 
(
    SOCIAL_PLATFORM_ID NUMBER,
    JOB_ID NUMBER,

    CONSTRAINT JOBS_OFFERED_ON_SOCIALS_PK PRIMARY KEY (SOCIAL_PLATFORM_ID, JOB_ID),
    CONSTRAINT JOOS_COMPANY_SOCIALS_FK FOREIGN KEY (SOCIAL_PLATFORM_ID) REFERENCES COMPANY_SOCIALS(SOCIAL_PLATFORM_ID),
    CONSTRAINT JOOS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);