-- Locations Table
CREATE TABLE LOCATIONS 
(
    LOCATION_ID NUMBER DEFAULT LOCATIONS_SEQ.NEXTVAL,
    LOCATION_NAME VARCHAR2(100),
    REGION VARCHAR2(100),
    COUNTRY VARCHAR2(100),

    CONSTRAINT LOCATIONS_PK PRIMARY KEY(LOCATION_ID)
);

-- Job Types Table
CREATE TABLE JOB_TYPES 
(
    JOB_TYPE_ID NUMBER DEFAULT JOB_TYPES_SEQ.NEXTVAL,
    JOB_TYPE_NAME VARCHAR2(100),
    JOB_TYPE_DESCRIPTION VARCHAR2(500),
    WORKING_HOURS NUMBER,

    CONSTRAINT JOB_TYPES_PK PRIMARY KEY(JOB_TYPE_ID)
);

-- Jobs Table
CREATE TABLE JOBS 
(
    JOB_ID NUMBER DEFAULT JOBS_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    JOB_TITLE VARCHAR2(100) NOT NULL,
    JOB_DESCRIPTION CLOB,
    JOB_SALARY NUMBER,
    JOB_QUALIFICATIONS VARCHAR2(500),
    REQUIRED_EXPERIENCE NUMBER,
    JOB_STATUS VARCHAR2(50),
    APPLICATION_DEADLINE DATE,
    JOB_TYPE_ID NUMBER,

    CONSTRAINT JOBS_PK PRIMARY KEY(JOB_ID),
    CONSTRAINT JOBS_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE,
    CONSTRAINT JOBS_TYPES_FK FOREIGN KEY (JOB_TYPE_ID) REFERENCES JOB_TYPES(JOB_TYPE_ID) ON DELETE CASCADE
);

-- Jobs Locations Junction Table
CREATE TABLE JOBS_LOCATIONS 
(
    JOB_ID NUMBER,
    LOCATION_ID NUMBER,
    WORK_MODE VARCHAR2(50),
    
    CONSTRAINT JOBS_LOCATIONS_PK PRIMARY KEY (JOB_ID, LOCATION_ID),
    CONSTRAINT LOCATIONS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT LOCATIONS_LOCATIONS_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE CASCADE
);

-- Required Skills Table
CREATE TABLE REQUIRED_SKILLS 
(
    SKILL_ID NUMBER DEFAULT REQUIRED_SKILLS_SEQ.NEXTVAL,
    SKILL_NAME VARCHAR2(100) NOT NULL,
    SKILL_LEVEL VARCHAR2(50),
    SKILL_DESCRIPTION VARCHAR2(500),

    CONSTRAINT REQUIRED_SKILLS_PK PRIMARY KEY(SKILL_ID)
);

-- Jobs Required Skills Junction Table
CREATE TABLE JOBS_REQUIRED_SKILLS 
(
    JOB_ID NUMBER,
    SKILL_ID NUMBER,
    SKILL_IMPORTANCE NUMBER,

    CONSTRAINT JOBS_REQUIRED_SKILLS_PK PRIMARY KEY (JOB_ID, SKILL_ID),
    CONSTRAINT JRS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT JRS_REQUIRED_SKILLS_FK FOREIGN KEY (SKILL_ID) REFERENCES REQUIRED_SKILLS(SKILL_ID) ON DELETE CASCADE
);

-- Jobs Offered on Socials Table
CREATE TABLE JOBS_OFFERED_ON_SOCIALS 
(
    SOCIAL_PLATFORM_ID NUMBER,
    JOB_ID NUMBER,

    CONSTRAINT JOBS_OFFERED_ON_SOCIALS_PK PRIMARY KEY (SOCIAL_PLATFORM_ID, JOB_ID),
    CONSTRAINT JOOS_COMPANY_SOCIALS_FK FOREIGN KEY (SOCIAL_PLATFORM_ID) REFERENCES COMPANY_SOCIALS(SOCIAL_PLATFORM_ID),
    CONSTRAINT JOOS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);