DROP TABLE COMPANY_PROFILE;
DROP TABLE COMPANY_BRANCHES;
DROP TABLE COMPANY_DEPARTMENT;
DROP TABLE COMPANY_SOCIALS;
DROP TABLE LOCATIONS;
DROP TABLE JOBS;
DROP TABLE REQUIRED_SKILLS;
DROP TABLE JOBS_REQUIRED_SKILLS;
DROP TABLE JOB_TYPES;
DROP TABLE JOBS_OFFERED_ON_SOCIALS;
DROP TABLE JOB_SEEKERS;
DROP TABLE RESUMES;
DROP TABLE WORK_EXP;
DROP TABLE RESUME_WORK_EXP;
DROP TABLE EDUCATION;
DROP TABLE RESUME_EDUCATION;
DROP TABLE APPLICATIONS;
DROP TABLE APPLICATION_STATUS;
DROP TABLE INTERVIEW_DETAILS;
DROP TABLE APP_FEEDBACK;
DROP TABLE FEEDBACKS;

DROP SEQUENCE COMPANY_PROFILE_SEQ;
DROP SEQUENCE COMPANY_BRANCHES_SEQ;
DROP SEQUENCE COMPANY_DEPARTMENT_SEQ;
DROP SEQUENCE COMPANY_SOCIALS_SEQ;
DROP SEQUENCE LOCATIONS_SEQ;
DROP SEQUENCE JOBS_SEQ;
DROP SEQUENCE REQUIRED_SKILLS_SEQ;
DROP SEQUENCE JOB_TYPES_SEQ;
DROP SEQUENCE JOB_SEEKERS_SEQ;
DROP SEQUENCE RESUMES_SEQ;
DROP SEQUENCE WORK_EXP_SEQ;
DROP SEQUENCE EDUCATION_SEQ;
DROP SEQUENCE APPLICATIONS_SEQ;
DROP SEQUENCE APPLICATION_STATUS_SEQ;
DROP SEQUENCE INTERVIEW_DETAILS_SEQ;
DROP SEQUENCE FEEDBACKS_SEQ;

-- Create Sequences for Primary Keys
CREATE SEQUENCE COMPANY_PROFILE_SEQ START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPANY_BRANCHES_SEQ START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPANY_DEPARTMENT_SEQ START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPANY_SOCIALS_SEQ START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LOCATIONS_SEQ START WITH 20000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE JOBS_SEQ START WITH 20000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REQUIRED_SKILLS_SEQ START WITH 20000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE JOB_TYPES_SEQ START WITH 20000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE JOB_SEEKERS_SEQ START WITH 30000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RESUMES_SEQ START WITH 30000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE WORK_EXP_SEQ START WITH 30000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDUCATION_SEQ START WITH 30000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPLICATIONS_SEQ START WITH 40000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPLICATION_STATUS_SEQ START WITH 40000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE INTERVIEW_DETAILS_SEQ START WITH 40000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE FEEDBACKS_SEQ START WITH 40000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create Tables
-- Company Profile Table
CREATE TABLE COMPANY_PROFILE 
(
    COMPANY_ID NUMBER DEFAULT COMPANY_PROFILE_SEQ.NEXTVAL,
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    COMPANY_ADDRESS VARCHAR2(200),
    COMPANY_SPECIALTY VARCHAR2(100),
    COMPANY_REQUIREMENTS VARCHAR2(500),
    COMPANY_BASE_SALARY NUMBER,
    COMPANY_PHONE_NUMBER VARCHAR2(20),
    COMPANY_SIZE NUMBER,

    CONSTRAINT COMPANY_PROFILE_PK PRIMARY KEY (COMPANY_ID)
);

-- Company Branches Table
CREATE TABLE COMPANY_BRANCHES 
(
    BRANCHES_ID NUMBER DEFAULT COMPANY_BRANCHES_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    BRANCH_ADDRESS VARCHAR2(200),
    BRANCH_SPECIALTY VARCHAR2(100),
    BRANCH_PHONE_NUMBER VARCHAR2(20),
    BRANCH_SIZE NUMBER,

    CONSTRAINT COMPANY_BRANCHES_PK PRIMARY KEY (BRANCHES_ID),
    CONSTRAINT BRANCHES_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE
);

-- Company Department Table
CREATE TABLE COMPANY_DEPARTMENT
(
    DEPARTMENT_ID NUMBER DEFAULT COMPANY_DEPARTMENT_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    DEPARTMENT_SPECIALTY VARCHAR2(100),
    DEPARTMENT_SIZE NUMBER,
    DEPARTMENT_PHONE_NUMBER VARCHAR2(20),
    DEPARTMENT_NAME VARCHAR2(100),

    CONSTRAINT COMPANY_DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT DEPARTMENT_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE
);

-- Company Socials Table
CREATE TABLE COMPANY_SOCIALS 
(
    SOCIAL_PLATFORM_ID NUMBER DEFAULT COMPANY_SOCIALS_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    COMPANY_WEBSITE VARCHAR2(200),
    COMPANY_APP VARCHAR2(100),
    COMPANY_SOCIAL_APPS VARCHAR2(200),

    CONSTRAINT COMPANY_SOCIALS_PK PRIMARY KEY(SOCIAL_PLATFORM_ID),
    CONSTRAINT SOCIALS_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE
);

-- Locations Table
CREATE TABLE LOCATIONS 
(
    LOCATION_ID NUMBER DEFAULT LOCATIONS_SEQ.NEXTVAL,
    LOCATION_NAME VARCHAR2(100),
    REGION VARCHAR2(100),
    COUNTRY VARCHAR2(100),

    CONSTRAINT LOCATIONS_PK PRIMARY KEY(LOCATION_ID)
);

-- Job Types Table
CREATE TABLE JOB_TYPES 
(
    JOB_TYPE_ID NUMBER DEFAULT JOB_TYPES_SEQ.NEXTVAL,
    JOB_TYPE_NAME VARCHAR2(100),
    JOB_TYPE_DESCRIPTION VARCHAR2(500),
    WORKING_HOURS NUMBER,

    CONSTRAINT JOB_TYPES_PK PRIMARY KEY(JOB_TYPE_ID)
);

-- Jobs Table
CREATE TABLE JOBS 
(
    JOB_ID NUMBER DEFAULT JOBS_SEQ.NEXTVAL,
    COMPANY_ID NUMBER,
    JOB_TITLE VARCHAR2(100) NOT NULL,
    JOB_DESCRIPTION CLOB,
    JOB_SALARY NUMBER,
    JOB_QUALIFICATIONS VARCHAR2(500),
    REQUIRED_EXPERIENCE NUMBER,
    JOB_STATUS VARCHAR2(50),
    APPLICATION_DEADLINE DATE,
    JOB_TYPE_ID NUMBER,

    CONSTRAINT JOBS_PK PRIMARY KEY(JOB_ID),
    CONSTRAINT JOBS_PROFILE_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_PROFILE(COMPANY_ID) ON DELETE CASCADE,
    CONSTRAINT JOBS_TYPES_FK FOREIGN KEY (JOB_TYPE_ID) REFERENCES JOB_TYPES(JOB_TYPE_ID) ON DELETE CASCADE
);

-- Jobs Locations Junction Table
CREATE TABLE JOBS_LOCATIONS 
(
    JOB_ID NUMBER,
    LOCATION_ID NUMBER,
    WORK_MODE VARCHAR2(50),
    
    CONSTRAINT JOBS_LOCATIONS_PK PRIMARY KEY (JOB_ID, LOCATION_ID),
    CONSTRAINT LOCATIONS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT LOCATIONS_LOCATIONS_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE CASCADE
);

-- Required Skills Table
CREATE TABLE REQUIRED_SKILLS 
(
    SKILL_ID NUMBER DEFAULT REQUIRED_SKILLS_SEQ.NEXTVAL,
    SKILL_NAME VARCHAR2(100) NOT NULL,
    SKILL_LEVEL VARCHAR2(50),
    SKILL_DESCRIPTION VARCHAR2(500),

    CONSTRAINT REQUIRED_SKILLS_PK PRIMARY KEY(SKILL_ID)
);

-- Jobs Required Skills Junction Table
CREATE TABLE JOBS_REQUIRED_SKILLS 
(
    JOB_ID NUMBER,
    SKILL_ID NUMBER,
    SKILL_IMPORTANCE NUMBER,

    CONSTRAINT JOBS_REQUIRED_SKILLS_PK PRIMARY KEY (JOB_ID, SKILL_ID),
    CONSTRAINT JRS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT JRS_REQUIRED_SKILLS_FK FOREIGN KEY (SKILL_ID) REFERENCES REQUIRED_SKILLS(SKILL_ID) ON DELETE CASCADE
);

-- Jobs Offered on Socials Table
CREATE TABLE JOBS_OFFERED_ON_SOCIALS 
(
    SOCIAL_PLATFORM_ID NUMBER,
    JOB_ID NUMBER,

    CONSTRAINT JOBS_OFFERED_ON_SOCIALS_PK PRIMARY KEY (SOCIAL_PLATFORM_ID, JOB_ID),
    CONSTRAINT JOOS_COMPANY_SOCIALS_FK FOREIGN KEY (SOCIAL_PLATFORM_ID) REFERENCES COMPANY_SOCIALS(SOCIAL_PLATFORM_ID),
    CONSTRAINT JOOS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);

-- Job Seekers Table
CREATE TABLE JOB_SEEKERS 
(
    JOB_SEEKER_ID NUMBER DEFAULT JOB_SEEKERS_SEQ.NEXTVAL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    ID_NUMBER VARCHAR2(50) UNIQUE,
    PHONE_NUMBER VARCHAR2(20),
    EMAIL_ADDRESS VARCHAR2(100) UNIQUE,
    JOB_PREFERENCE VARCHAR2(200),

    CONSTRAINT JOB_SEEKERS_PK PRIMARY KEY(JOB_SEEKER_ID)
);

-- Resume Table
CREATE TABLE RESUMES 
(
    RESUME_ID NUMBER DEFAULT RESUMES_SEQ.NEXTVAL,
    JOB_SEEKER_ID NUMBER,
    FILE_NAME VARCHAR2(200),
    FILE_FORMAT VARCHAR2(50),
    UPLOAD_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT RESUMES_PK PRIMARY KEY(RESUME_ID),
    CONSTRAINT RESUMES_SEEKERS_FK FOREIGN KEY (JOB_SEEKER_ID) REFERENCES JOB_SEEKERS(JOB_SEEKER_ID) ON DELETE CASCADE
);

-- Work Experience Table
CREATE TABLE WORK_EXP 
(
    WORK_EXPERIENCE_ID NUMBER DEFAULT WORK_EXP_SEQ.NEXTVAL,
    JOB_SEEKER_ID NUMBER,
    COMPANY_NAME VARCHAR2(100),
    JOB_TITLE VARCHAR2(100),
    START_DATE DATE,
    END_DATE DATE,

    CONSTRAINT WORK_EXP_PK PRIMARY KEY(WORK_EXPERIENCE_ID),
    CONSTRAINT WORK_EXP_SEEKERS_FK FOREIGN KEY (JOB_SEEKER_ID) REFERENCES JOB_SEEKERS(JOB_SEEKER_ID) ON DELETE CASCADE
);

-- Resume Work Experience Junction Table
CREATE TABLE RESUME_WORK_EXP 
(
    RESUME_ID NUMBER,
    WORK_EXPERIENCE_ID NUMBER,

    CONSTRAINT RESUME_WORK_EXP_PK PRIMARY KEY (RESUME_ID, WORK_EXPERIENCE_ID),
    CONSTRAINT RWE_RESUMES_FK FOREIGN KEY (RESUME_ID) REFERENCES RESUMES(RESUME_ID) ON DELETE CASCADE,
    CONSTRAINT RWE_WORK_EXP_FK FOREIGN KEY (WORK_EXPERIENCE_ID) REFERENCES WORK_EXP(WORK_EXPERIENCE_ID) ON DELETE CASCADE
);

-- Education Table
CREATE TABLE EDUCATION 
(
    EDUCATION_ID NUMBER DEFAULT EDUCATION_SEQ.NEXTVAL,
    JOB_SEEKER_ID NUMBER,
    QUALIFICATION VARCHAR2(200),
    COURSE VARCHAR2(200),
    INSTITUTION_NAME VARCHAR2(200),
    GRADUATION_YEAR NUMBER,
    CGPA NUMBER,

    CONSTRAINT EDUCATION_PK PRIMARY KEY(EDUCATION_ID),
    CONSTRAINT EDUCATION_SEEKERS_FK FOREIGN KEY (JOB_SEEKER_ID) REFERENCES JOB_SEEKERS(JOB_SEEKER_ID) ON DELETE CASCADE
);

-- Resume Education Junction Table
CREATE TABLE RESUME_EDUCATION 
(
    RESUME_ID NUMBER,
    EDUCATION_ID NUMBER,

    CONSTRAINT RESUME_EDUCATION_PK PRIMARY KEY (RESUME_ID, EDUCATION_ID),
    CONSTRAINT RE_RESUMES_FK FOREIGN KEY (RESUME_ID) REFERENCES RESUMES(RESUME_ID) ON DELETE CASCADE,
    CONSTRAINT RE_EDUCATION_FK FOREIGN KEY (EDUCATION_ID) REFERENCES EDUCATION(EDUCATION_ID) ON DELETE CASCADE
);

-- Interview Details Table
CREATE TABLE INTERVIEW_DETAILS 
(
    INTERVIEW_ID NUMBER DEFAULT INTERVIEW_DETAILS_SEQ.NEXTVAL,
    INTERVIEW_DATE DATE,
    INTERVIEWER_NAME VARCHAR2(100),

    CONSTRAINT INTERVIEW_DETAILS_PK PRIMARY KEY(INTERVIEW_ID)
);

-- Application Status Table
CREATE TABLE APPLICATION_STATUS 
(
    STATUS_ID NUMBER DEFAULT APPLICATION_STATUS_SEQ.NEXTVAL,
    STATUS_NAME VARCHAR2(50),
    STATUS_LAST_UPDATE DATE,
    STATUS_ISFINAL CHAR(1),

    CONSTRAINT APPLICATION_STATUS_PK PRIMARY KEY(STATUS_ID)
);

-- Applications Table
CREATE TABLE APPLICATIONS 
(
    APPLICATION_ID NUMBER DEFAULT APPLICATIONS_SEQ.NEXTVAL,
    JOB_ID NUMBER,
    JOB_SEEKER_ID NUMBER,
    INTERVIEW_ID NUMBER,
    DATE_APPLIED DATE DEFAULT SYSDATE,
    STATUS_ID NUMBER,

    CONSTRAINT APPLICATIONS_PK PRIMARY KEY(APPLICATION_ID),
    CONSTRAINT APPLICATIONS_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT APPLICATIONS_SEEKERS_FK FOREIGN KEY (JOB_SEEKER_ID) REFERENCES JOB_SEEKERS(JOB_SEEKER_ID) ON DELETE CASCADE,
    CONSTRAINT APPLICATIONS_IVDETAILS_FK FOREIGN KEY (INTERVIEW_ID) REFERENCES INTERVIEW_DETAILS(INTERVIEW_ID) ON DELETE CASCADE,
    CONSTRAINT APPLICATIONS_APPSTATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES APPLICATION_STATUS(STATUS_ID) ON DELETE CASCADE
);

-- Feedbacks Table
CREATE TABLE FEEDBACKS 
(
    FEEDBACK_ID NUMBER DEFAULT FEEDBACKS_SEQ.NEXTVAL,
    APPLICATION_ID NUMBER,
    MESSAGE CLOB,
    DATE_SENT DATE DEFAULT SYSDATE,

    CONSTRAINT FEEDBACKS_PK PRIMARY KEY(FEEDBACK_ID),
    CONSTRAINT FEEDBACKS_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID) ON DELETE CASCADE
);

-- Application Feedback Junction Table
CREATE TABLE APP_FEEDBACK 
(
    APPLICATION_ID NUMBER,
    FEEDBACK_ID NUMBER,

    CONSTRAINT APP_FEEDBACK_PK PRIMARY KEY (APPLICATION_ID, FEEDBACK_ID),
    CONSTRAINT APP_FEEDBACK_APPLICATIONS_FK FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID),
    CONSTRAINT APP_FEEDBACK_FEEDBACKS_FK FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACKS(FEEDBACK_ID)
);