DROP TABLE TALENT_BRIDGE_ACC_USER;
DROP SEQUENCE TALENT_BRIDGE_ACC_USER_SEQ;

-- Creating sequences
CREATE SEQUENCE TALENT_BRIDGE_ACC_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create tables
CREATE TABLE TALENT_BRIDGE_ACC_USER
(
    ACC_USER_ID INTEGER DEFAULT TALENT_BRIDGE_ACC_USER_SEQ.NEXTVAL,
    ACC_USER_ROLE VARCHAR2(30) DEFAULT 'Member',
    ACC_USER_EMAIL VARCHAR2(30),
    ACC_USER_PWD VARCHAR2(20),
    ACC_USER_FNAME VARCHAR2(30),
    ACC_USER_LNAME VARCHAR2(30),
    ACC_USER_NATIONALITY VARCHAR2(30),
    ACC_USER_PROFILE_PIC BLOB,

    CONSTRAINT TB_ACC_USER_PK PRIMARY KEY(ACC_USER_ID)
);

-- Insertions
INSERT INTO TALENT_BRIDGE_ACC_USER VALUES(DEFAULT, 'Admin', 'talentbridgeadmin@gmail.com', 123456, 'Ammar Danial', 'Abdullah', 'Malaysia', NULL);
INSERT INTO TALENT_BRIDGE_ACC_USER VALUES(DEFAULT, 'Member', 'melissa@gmail.com', 123456, 'Melissa', 'Fionne', 'Malaysia', NULL);
INSERT INTO TALENT_BRIDGE_ACC_USER VALUES(DEFAULT, 'Member', 'julia@gmail.com', 123456, 'Julia', 'Thong', 'Malaysia', NULL);